# syntax=docker/dockerfile:1

# Tool: beads (bd)

FROM repo-base:latest AS tool_beads
LABEL tools=true

USER root

RUN curl -fsSL https://raw.githubusercontent.com/steveyegge/beads/main/scripts/install.sh | bash \
    && if [ -f /root/.local/bin/bd ]; then \
        mv /root/.local/bin/bd /usr/local/bin/bd; \
    fi \
    && chmod +x /usr/local/bin/bd \
    && ln -sf /usr/local/bin/bd /usr/local/bin/beads \
    && test -x /usr/local/bin/bd \
    && test -L /usr/local/bin/beads

USER devuser
