# syntax=docker/dockerfile:1

FROM repo-base:latest AS tool_fzf

LABEL tools=true

USER root

RUN git clone --depth 1 https://github.com/junegunn/fzf.git /root/.fzf \
    && /root/.fzf/install \
    && cp /root/.fzf/bin/fzf /usr/local/bin/fzf \
    && chmod +x /usr/local/bin/fzf

ENV PATH="/root/.fzf/bin:${PATH}"

USER devuser
